# Generated by Django 4.2.3 on 2023-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Finance - Pune', 'Finance-Pune'), ('Finance - Begaluru', 'Finance - Bengaluru'), ('HR - Pune', 'HR - Pune'), ('HR - Begaluru', 'HR - Bengaluru'), ('IT - Pune', 'IT-Pune'), ('IT - Begaluru', 'IT - Bengaluru'), ('Marketing - Pune', 'Marketing-Pune'), ('Marketing - Begaluru', 'Marketing - Bengaluru')], max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Analyst', 'Analyst'), ('Data Analyst', 'Data Analyst'), ('HR Manager', 'HR Manager'), ('Software Engineer', 'Software Engineer'), ('Python Developer', 'Python Developer'), ('Sales Executive', 'Sales Executive'), ('Java Developer', 'Java Developer'), ('Intern', 'Intern'), ('Sales Executive', 'Sales Executive'), ('SQL Developer', 'SQL Developer'), ('Project Manager', 'Project Manager')], max_length=50),
        ),
    ]
