# Generated by Django 4.2.3 on 2023-07-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_department_location_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Finance - Pune', 'Finance-Pune'), ('Finance - Begaluru', 'Finance - Bengaluru'), ('HR - Pune', 'HR - Pune'), ('HR - Bengaluru', 'HR - Bengaluru'), ('IT - Pune', 'IT-Pune'), ('IT - Begaluru', 'IT - Bengaluru'), ('Marketing - Pune', 'Marketing-Pune'), ('Marketing - Begaluru', 'Marketing - Bengaluru')], max_length=50),
        ),
    ]
